builds:
  - id: builder
    binary: packer-builder-veertu-anka
    env:
      # Because we want to avoid coupling to system libraries.
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64

archives:
  - id: default
    builds:
      - builder
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: false
    files: []
  - id: zip
    builds:
      - builder
    format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    wrap_in_directory: false
    files: []

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

signs:
  - id: notarize-default
    signature: "${artifact}.tar.gz"
    cmd: gon
    args:
      - ".gon.hcl"
    artifacts: all
    ids:
      - builder
  - id: notarize-zip
    signature: "${artifact}.zip"
    cmd: gon
    args:
      - ".gon.hcl"
    artifacts: all
    ids:
      - builder

release:
  ids:
    - default
    - zip
  # swap to false once happy with release pipeline.
  draft: true
