name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:

  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Describe plugin
        id: plugin_describe
        run: echo "::set-output name=api_version::$(go run . describe | jq -r '.api_version')"
      - name: Run GoReleaser check
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check
      - name: Run GoReleaser build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --single-target --snapshot --rm-dist