name: Check PR

on:
  pull_request:
    branches: [ master ]

jobs:

  check-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install Deps
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sudo sh -s -- -b /usr/local/bin v1.40.1

    - name: Build & Install
      run: make clean go.hcl2spec go.build install

    - name: Lint
      run: make lint go.lint
      
    - name: Test
      run: make go.test
